# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import yummy_receitas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=yummy_receitas.models.get_image_path)),
                ('categoria', models.TextField()),
                ('ingredientes', models.TextField()),
                ('tempo_preparo', models.TextField()),
                ('instrucoes_preparo', models.TextField()),
                ('porcoes', models.TextField()),
                ('valor_nutricional', models.TextField()),
                ('metodo_cozimento', models.TextField()),
            ],
            options={
                'verbose_name': 'receita',
            },
        ),
    ]
