# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='CategoryMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membershipCategoria', to='yummy_receitas.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=200, null=True)),
                ('unidade', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'ingrediente',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=200, null=True)),
                ('autor', models.CharField(max_length=200, null=True)),
                ('descricao', models.TextField()),
                ('imagem', models.CharField(max_length=200, null=True)),
                ('video', models.CharField(max_length=200, null=True)),
                ('tempo_preparo', models.CharField(max_length=10, null=True)),
                ('instrucoes_preparo', models.TextField(null=True)),
                ('porcoes', models.CharField(max_length=200, null=True)),
                ('valor_nutricional', models.TextField(null=True)),
                ('metodo_cozimento', models.CharField(max_length=200, null=True)),
                ('categoria', models.ManyToManyField(related_name='categorias', through='yummy_receitas.CategoryMember', to='yummy_receitas.Categoria')),
                ('ingredientes', models.ManyToManyField(related_name='ingredientes', through='yummy_receitas.IngredientDetail', to='yummy_receitas.Ingrediente')),
            ],
            options={
                'verbose_name': 'receita',
            },
        ),
        migrations.AddField(
            model_name='ingredientdetail',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membershipReceita', to='yummy_receitas.Ingrediente'),
        ),
        migrations.AddField(
            model_name='ingredientdetail',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membershipReceita', to='yummy_receitas.Receita'),
        ),
        migrations.AddField(
            model_name='categorymember',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membershipCategoria', to='yummy_receitas.Receita'),
        ),
    ]
