# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import yummy_receitas.models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_receitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoria',
            },
        ),
        migrations.AddField(
            model_name='receita',
            name='autor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to=yummy_receitas.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummy_receitas.Categoria'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='ingredientes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='instrucoes_preparo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='metodo_cozimento',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='porcoes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor_nutricional',
            field=models.TextField(null=True),
        ),
    ]
