# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_receitas', '0003_auto_20171113_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='metodo_cozimento',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='MetodoCozimento',
        ),
    ]
